# Generated by Django 3.2 on 2021-04-20 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_historicalsettings_history_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'permissions': [('change_reports_settings', 'Can change Reports settings')], 'verbose_name_plural': 'Settings'},
        ),
    ]
