# Generated by Django 3.2 on 2021-04-18 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_building_name_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='tenant',
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to='users.tenant'),
        ),
    ]
