# Generated by Django 3.2 on 2021-04-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210418_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsettings',
            name='choice_user_signup_method',
            field=models.CharField(choices=[('Tenant Distributes Signup URL', 'Tenant Distributes Signup URL')], default='Tenant Distributes Signup URL', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('AWAITING', 'Awaiting Approval'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CHANGE_REQUEST', 'Change Requested'), ('CANCELLED', 'Cancelled'), ('STATE_0', 'State0 Start'), ('STATE_1', 'State1 Where'), ('STATE_2', 'State2 Time'), ('STATE_3A', 'State3A Selection Packages'), ('STATE_3B', 'State3B Selection Choices'), ('STATE_4', 'State4 Details')], default='Pending', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='choice_user_signup_method',
            field=models.CharField(choices=[('Tenant Distributes Signup URL', 'Tenant Distributes Signup URL')], default='Tenant Distributes Signup URL', max_length=32),
        ),
    ]
