# Generated by Django 3.2 on 2021-04-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210419_0103'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='billingrecord',
            managers=[
            ],
        ),
    ]
